services:
  - type: web
    name: vodila-app
    env: docker
    region: frankfurt
    plan: starter
    buildCommand: ""
    startCommand: uv run uvicorn vodila.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: RENDER
        value: "true"
      - key: AUDIO_PATH
        value: /app/vodila/audio
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
